<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExerciseSeeder extends Seeder
{
    public function run(): void
    {
        $exercises = [
            // ── KNEE ──────────────────────────────────────────────────────────
            [
                'title'        => 'Quad Sets',
                'description'  => 'Tighten the quadriceps muscle while the leg is straight, hold for 5 seconds.',
                'category'     => 'strengthening',
                'body_part'    => 'knee',
                'difficulty'   => 'beginner',
                'duration_sec' => 300,
                'sets'         => 3,
                'reps'         => 10,
                'rest_sec'     => 30,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'Sit or lie with leg straight.',
                    'Tighten thigh muscle by pressing knee down.',
                    'Hold for 5 seconds, then relax.',
                    'Repeat 10 times, 3 sets.',
                ]),
                'equipment'    => json_encode([]),
                'is_active'    => true,
            ],
            [
                'title'        => 'Straight Leg Raises',
                'description'  => 'Strengthen quadriceps without bending the knee joint.',
                'category'     => 'strengthening',
                'body_part'    => 'knee',
                'difficulty'   => 'beginner',
                'duration_sec' => 360,
                'sets'         => 3,
                'reps'         => 15,
                'rest_sec'     => 45,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'Lie on your back.',
                    'Bend the uninvolved knee, foot flat.',
                    'Tighten quads on injured leg, raise to 45°.',
                    'Hold 2 seconds, lower slowly.',
                ]),
                'equipment'    => json_encode([]),
                'is_active'    => true,
            ],
            [
                'title'        => 'Terminal Knee Extension (TKE)',
                'description'  => 'Strengthen the final degrees of knee extension with a resistance band.',
                'category'     => 'strengthening',
                'body_part'    => 'knee',
                'difficulty'   => 'intermediate',
                'duration_sec' => 300,
                'sets'         => 3,
                'reps'         => 15,
                'rest_sec'     => 30,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'Loop a resistance band behind your knee and anchor it in front.',
                    'Stand with slight knee bend.',
                    'Straighten the knee against the band resistance.',
                    'Hold 2s, slowly return.',
                ]),
                'equipment'    => json_encode(['resistance_band']),
                'is_active'    => true,
            ],
            [
                'title'        => 'Short Arc Quads',
                'description'  => 'Isolate the last 30° of knee extension to strengthen the quad.',
                'category'     => 'strengthening',
                'body_part'    => 'knee',
                'difficulty'   => 'beginner',
                'duration_sec' => 240,
                'sets'         => 3,
                'reps'         => 10,
                'rest_sec'     => 30,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'Place a rolled towel under the knee (30° bend).',
                    'Straighten the knee fully.',
                    'Hold 5 seconds, lower slowly.',
                ]),
                'equipment'    => json_encode(['towel']),
                'is_active'    => true,
            ],
            [
                'title'        => 'Knee Flexion Stretch',
                'description'  => 'Heel slides to restore knee bending range of motion.',
                'category'     => 'flexibility',
                'body_part'    => 'knee',
                'difficulty'   => 'beginner',
                'duration_sec' => 300,
                'sets'         => 3,
                'reps'         => 10,
                'rest_sec'     => 20,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'Lie on back.',
                    'Slide heel toward buttocks, bending knee.',
                    'Hold at maximum bend for 5 seconds.',
                    'Slide back to start.',
                ]),
                'equipment'    => json_encode([]),
                'is_active'    => true,
            ],

            // ── SPINE / BACK ───────────────────────────────────────────────
            [
                'title'        => 'Pelvic Tilt',
                'description'  => 'Activate deep core stabilisers and relieve lower back pain.',
                'category'     => 'core_stability',
                'body_part'    => 'spine',
                'difficulty'   => 'beginner',
                'duration_sec' => 300,
                'sets'         => 3,
                'reps'         => 10,
                'rest_sec'     => 20,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'Lie on back, knees bent, feet flat.',
                    'Flatten lower back against floor.',
                    'Hold 5 seconds, then relax.',
                    'Repeat 10 times.',
                ]),
                'equipment'    => json_encode([]),
                'is_active'    => true,
            ],
            [
                'title'        => 'Dead Bug',
                'description'  => 'Core stability exercise maintaining neutral spine while moving limbs.',
                'category'     => 'core_stability',
                'body_part'    => 'spine',
                'difficulty'   => 'intermediate',
                'duration_sec' => 360,
                'sets'         => 3,
                'reps'         => 8,
                'rest_sec'     => 45,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'Lie on back, arms straight to ceiling, knees at 90° in air.',
                    'Flatten spine against floor — maintain throughout.',
                    'Lower opposite arm and leg toward floor.',
                    'Return and repeat on other side.',
                ]),
                'equipment'    => json_encode([]),
                'is_active'    => true,
            ],
            [
                'title'        => 'Bird Dog',
                'description'  => 'Spinal stabilisation exercise on hands and knees.',
                'category'     => 'core_stability',
                'body_part'    => 'spine',
                'difficulty'   => 'intermediate',
                'duration_sec' => 360,
                'sets'         => 3,
                'reps'         => 10,
                'rest_sec'     => 30,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'Start on hands and knees (tabletop).',
                    'Keep back flat and core engaged.',
                    'Extend opposite arm and leg simultaneously.',
                    'Hold 3 seconds, return, repeat.',
                ]),
                'equipment'    => json_encode([]),
                'is_active'    => true,
            ],
            [
                'title'        => 'Cat-Cow Stretch',
                'description'  => 'Improve spinal mobility and relieve stiffness.',
                'category'     => 'flexibility',
                'body_part'    => 'spine',
                'difficulty'   => 'beginner',
                'duration_sec' => 240,
                'sets'         => 1,
                'reps'         => 15,
                'rest_sec'     => 0,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'On hands and knees, neutral spine.',
                    'Inhale: drop belly, look up (Cow).',
                    'Exhale: round back, tuck chin (Cat).',
                    'Move slowly and rhythmically.',
                ]),
                'equipment'    => json_encode([]),
                'is_active'    => true,
            ],
            [
                'title'        => 'McGill Curl-Up',
                'description'  => 'Safe abdominal exercise that spares spinal compression.',
                'category'     => 'core_stability',
                'body_part'    => 'spine',
                'difficulty'   => 'beginner',
                'duration_sec' => 300,
                'sets'         => 3,
                'reps'         => 8,
                'rest_sec'     => 30,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'Lie on back, one knee bent, other leg straight.',
                    'Place hands under lumbar curve.',
                    'Lift head and shoulders only.',
                    'Hold 10 seconds, lower slowly.',
                ]),
                'equipment'    => json_encode([]),
                'is_active'    => true,
            ],

            // ── SHOULDER ──────────────────────────────────────────────────
            [
                'title'        => 'Pendulum Exercise',
                'description'  => 'Gentle passive shoulder mobilisation using gravity.',
                'category'     => 'range_of_motion',
                'body_part'    => 'shoulder',
                'difficulty'   => 'beginner',
                'duration_sec' => 300,
                'sets'         => 3,
                'reps'         => 20,
                'rest_sec'     => 60,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'Lean forward, let injured arm hang.',
                    'Use body sway to make small circles.',
                    'Gradually increase circle size.',
                    'Switch direction after 20 circles.',
                ]),
                'equipment'    => json_encode([]),
                'is_active'    => true,
            ],
            [
                'title'        => 'Shoulder External Rotation (Band)',
                'description'  => 'Strengthen rotator cuff external rotators.',
                'category'     => 'strengthening',
                'body_part'    => 'shoulder',
                'difficulty'   => 'intermediate',
                'duration_sec' => 300,
                'sets'         => 3,
                'reps'         => 15,
                'rest_sec'     => 45,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'Hold band with elbow at 90°, elbow against side.',
                    'Rotate forearm outward, keeping elbow tucked.',
                    'Slowly return to start.',
                    '3 sets of 15 reps.',
                ]),
                'equipment'    => json_encode(['resistance_band']),
                'is_active'    => true,
            ],
            [
                'title'        => 'Scapular Retraction',
                'description'  => 'Strengthen mid-traps and improve posture.',
                'category'     => 'strengthening',
                'body_part'    => 'shoulder',
                'difficulty'   => 'beginner',
                'duration_sec' => 240,
                'sets'         => 3,
                'reps'         => 15,
                'rest_sec'     => 30,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'Sit or stand with arms at sides.',
                    'Squeeze shoulder blades together and down.',
                    'Hold 5 seconds.',
                    'Release and repeat.',
                ]),
                'equipment'    => json_encode([]),
                'is_active'    => true,
            ],

            // ── HIP ───────────────────────────────────────────────────────
            [
                'title'        => 'Clamshells',
                'description'  => 'Activate hip abductors and external rotators (glute medius).',
                'category'     => 'strengthening',
                'body_part'    => 'hip',
                'difficulty'   => 'beginner',
                'duration_sec' => 300,
                'sets'         => 3,
                'reps'         => 20,
                'rest_sec'     => 30,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'Lie on side, knees bent, feet together.',
                    'Keeping feet together, rotate top knee upward.',
                    'Raise as high as possible without rolling pelvis.',
                    'Lower slowly, repeat.',
                ]),
                'equipment'    => json_encode([]),
                'is_active'    => true,
            ],
            [
                'title'        => 'Hip Bridge',
                'description'  => 'Strengthen glutes and reduce lower back pain.',
                'category'     => 'strengthening',
                'body_part'    => 'hip',
                'difficulty'   => 'beginner',
                'duration_sec' => 300,
                'sets'         => 3,
                'reps'         => 15,
                'rest_sec'     => 30,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'Lie on back, knees bent, feet hip-width apart.',
                    'Squeeze glutes and lift hips to shoulder height.',
                    'Hold 2 seconds at top.',
                    'Lower slowly, do not slam hips down.',
                ]),
                'equipment'    => json_encode([]),
                'is_active'    => true,
            ],

            // ── ANKLE ─────────────────────────────────────────────────────
            [
                'title'        => 'Ankle Alphabet',
                'description'  => 'Active range of motion exercise for the ankle joint.',
                'category'     => 'range_of_motion',
                'body_part'    => 'ankle',
                'difficulty'   => 'beginner',
                'duration_sec' => 300,
                'sets'         => 3,
                'reps'         => 1,
                'rest_sec'     => 30,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'Sit with foot off the ground.',
                    'Trace each letter of the alphabet using your foot.',
                    'Keep movements deliberate and full range.',
                    'Repeat 3 sets.',
                ]),
                'equipment'    => json_encode([]),
                'is_active'    => true,
            ],
            [
                'title'        => 'Calf Raises',
                'description'  => 'Strengthen the gastrocnemius and soleus muscles.',
                'category'     => 'strengthening',
                'body_part'    => 'ankle',
                'difficulty'   => 'beginner',
                'duration_sec' => 300,
                'sets'         => 3,
                'reps'         => 20,
                'rest_sec'     => 45,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'Stand behind a chair for balance.',
                    'Rise up on toes as high as possible.',
                    'Hold 1 second at top.',
                    'Lower slowly (3 seconds down).',
                ]),
                'equipment'    => json_encode(['chair']),
                'is_active'    => true,
            ],

            // ── GENERAL / BALANCE ─────────────────────────────────────────
            [
                'title'        => 'Single Leg Balance',
                'description'  => 'Improve proprioception and balance on the injured limb.',
                'category'     => 'balance',
                'body_part'    => 'general',
                'difficulty'   => 'beginner',
                'duration_sec' => 300,
                'sets'         => 3,
                'reps'         => 1,
                'rest_sec'     => 30,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'Stand near a wall for safety.',
                    'Lift one foot and balance for 30 seconds.',
                    'Progress: eyes closed, unstable surface.',
                    '3 sets each side.',
                ]),
                'equipment'    => json_encode([]),
                'is_active'    => true,
            ],
            [
                'title'        => 'Deep Breathing',
                'description'  => 'Diaphragmatic breathing to activate core and reduce pain sensitisation.',
                'category'     => 'breathing',
                'body_part'    => 'general',
                'difficulty'   => 'beginner',
                'duration_sec' => 300,
                'sets'         => 1,
                'reps'         => 10,
                'rest_sec'     => 0,
                'video_url'    => null,
                'thumbnail_url'=> null,
                'instructions' => json_encode([
                    'Sit comfortably, place one hand on belly.',
                    'Inhale slowly through nose for 4 seconds.',
                    'Feel belly rise (not chest).',
                    'Exhale through mouth for 6 seconds.',
                ]),
                'equipment'    => json_encode([]),
                'is_active'    => true,
            ],
        ];

        $now = now()->toDateTimeString();
        foreach ($exercises as &$e) {
            $e['created_at'] = $now;
            $e['updated_at'] = $now;
        }

        DB::table('exercises')->insertOrIgnore($exercises);
    }
}
